repos:

-   repo: https://github.com/pycqa/isort
    rev: 9.0.1
    hooks:
    - id: isort
      name: isort (python)
      args: [ "--profile", "black", "--filter-files" ]

-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.5.1
    hooks:
    -   id: black

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v2.3.1"
    hooks:
    -   id: mypy
        entry: bash -c 'mypy --no-strict-optional --ignore-missing-imports -p hashtablebot'
        verbose: true

-   repo: local
    hooks:
        - id: unittest
          name: unittest
          entry: python -m unittest discover
          language: python
          'types': [ python ]
          pass_filenames: false
          stages: [ pre-commit ]
          additional_dependencies:
            - twitchio
