services:
  bot:
    container_name: bot
    build: .
    working_dir: /hashtablebot
    command: "python3 main.py 1> bot_output 2> bot_errors"
    environment:
      - PYTHONPATH=/
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:15.1-alpine
    env_file:
      - .env
